times = ['Botafogo', 'Flamengo', 'Grêmio', 'São Paulo', 'Fluminense', 'Palmeiras', 'Bragantino', 'Athletico-PR', 'Fortaleza', 'Cruzeiro', 'Internacional', 'Atlético-MG', 'Cuiabá', 'Santos', 'Corinthians', 'Bahia', 'Goiás', 'Coritiba', 'Vasco da Gama', 'América-MG']
print('-='*20)
print(f"Lista de Times do Brasileirão: {times}")
print('-='*20)
print(f"Os 5 primeiros são {times[0:6]}")
print('-='*20)
print(f"Os 4 últimos são {times[16:]}")
print('-='*20)
print(f"Times em ordem alfabética: {sorted(times)}")
print('-='*20)
print(f"O São Paulo está em {times.index('São Paulo')+1}° lugar")
