p=input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(p,type(p)))
print('Só tem espaços: {}'.format(p.isspace()))
print('É numérico: {}'.format(p.isnumeric()))
print('É alfabético: {}'.format(p.isalpha()))
print('É alfanumérico: {}'.format(p.isalnum()))
print('Está todo em maiúsculo: {}'.format(p.isupper()))
print('Está todo em minúsculo: {}'.format(p.islower()))
print('Está capitalizado: {}'.format(p.istitle()))